export const INIT_STORAGE = "INIT_STORAGE";
export const INIT_STORAGE_FROM_TEMPLATE = "INIT_STORAGE_FROM_TEMPLATE";
export const INIT_STORAGE_FROM_LOCALSTORAGE = "INIT_STORAGE_FROM_LOCALSTORAGE";
export const INIT_STORAGE_ERROR = "INIT_STORAGE_ERROR";
