export const INIT_STORAGE = "INIT_STORAGE";
export const INIT_STORAGE_FROM_TEMPLATE = "INIT_STORAGE_FROM_TEMPLATE";
export const INIT_STORAGE_FROM_LOCALSTORAGE = "INIT_STORAGE_FROM_LOCALSTORAGE";
export const INIT_STORAGE_ERROR = "INIT_STORAGE_ERROR";
export const GET_CURRENT_TASK = "GET_CURRENT_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";
